### ISSUE TITLE
Locate coordinates from image

### ISSUE THREAD

**Issue by quintendewilde** [apple/ml-hypersim#14]
Would hypersim be able to get me the horizontal coordinates of an object in an image?

I'm relating this to this paper/project that uses coordinates to create 3D shapes from 3 single images with there coordinates for focal point, polar coordinates and distance from object to camera? 

Or is this beyond the scope of this project?

**Comment by mikeroberts3000** [comment]
I don't I understand your question. Can you describe it more precisely? Here are the things I don't understand in your question.

- What are the "horizontal coordinates" of an object?
- You said "I'm relating THIS to this paper..." What does the first THIS refer to in this sentence?
- What are "there coordinates for focal point"? Do you mean "their coordinates for focal point"? If so, who is "their" referring to? I don't know what paper you're talking about.
- I know what polar coordinates are, but I don't know what you mean by polar coordinates in this context.

**Comment by quintendewilde** [comment]
Hi sorry for the vagueness, 

This is the project I'm working with https://github.com/walsvid/Pixel2MeshPlusPlus

For creating custom input (real images to 3D render) I need from an object in an image  the azimuth, elevation, in-plane rotation, distance, the field of view. 

https://en.wikipedia.org/wiki/Horizontal_coordinate_system

The original project creates these images from a 3D environment. I think it would be more usefull if this could be generated from three images (maybe processed or photoshopped to isolate the object from the image)

**Comment by mikeroberts3000** [comment]
I'm sorry but I still don't understand your question.
