### ISSUE TITLE
Questions about the intrinsic components

### ISSUE THREAD

**Issue by tlsshh** [apple/ml-hypersim#16]
Thank you for releasing such a great dataset!

I have some questions about the intrinsic components:

- According to your paper, I can understand the diffuse illumination, the diffuse reflectance, and the residual. However, I don't know what is the gamma image, the non-lambertian image and the tonemap image. And why the residual image and the non-lambertian image are two different images?
- I guess the lambertian image is **diffuse illumination X diffuse reflectance**.
- I guess you visualize the color image via both tonemapping and gamma correction. Am I right?

**Comment by mikeroberts3000** [comment]
Hi! Great questions. Here is a quick high-level description of each image in the `scene_cam_XX_final_preview` folder.

- `color` is the color image produced the renderer without tonemapping and without gamma correction.
- `diff` measures how well the `diffuse_reflectance`, `diffuse_illumination`, and `residual` images reconstruct the color image; it is calculated as `diff = abs(color - (diffuse_reflectance*diffuse_illumination + residual))`.
- `diffuse_illumination` is described in the paper.
- `diffuse_reflectance` is described in the paper.
- `gamma` is the `color` image without tonemapping and with gamma correction.
- `lambertian` is the reconstructed color image excluding all non-diffuse energy; it is calculated as `lambertian = diffuse_reflectance*diffuse_illumination`
- `non_lambertian` is the reconstructed color image including all non-diffuse energy; this image should closely match the `color` image. it is calculated as `non_lambertian = diffuse_reflectance*diffuse_illumination + residual`.
- `residual` is described in the paper.
- `tonemap` is the `color` image with tonemapping and with gamma correction.

You can see for yourself how each of these preview images is calculated in `code/python/tools/generate_hdf5_from_vrimg.py` and `code/python/tools/scene_generate_images_tonemap.py`.
