### ISSUE TITLE
Generating axis-aligned images

### ISSUE THREAD

**Issue by americast** [apple/ml-hypersim#17]
Hi, I wanted to know how I may generate axis-aligned scene images. Most of the images seem to have been captured from a camera that was tilted at various degrees. It would be very helpful if I could either rotate those images to make them axis-aligned or generate scene images from a camera that is not tilted. Thanks!

**Comment by mikeroberts3000** [comment]
Hi! All of our camera poses are given in the ground truth data. See our README for a detailed description of precisely how they're stored, and precisely how to interpret the stored values.

Given the camera rotation matrix for a particular image, you can find the "roll angle" you're looking for with a bit of linear algebra. Roughly speaking, you want to rotate the camera rotation matrix about its "forward" direction, such that its "right" direction lies in the horizontal plane. Stating this problem more precisely, you want to find a rotation matrix `R`, parameterized by a roll angle `theta`, such that the following condition holds:

```
# rotate our camera and return the camera's new right vector
rotated_camera_right_vector = get_right_vector(R(theta)*original_camera_rotation_matrix))
```
```
# compute the right vector that lies in the horizontal plane
original_camera_forward_vector = get_forward_vector(original_camera_rotation_matrix)
rotated_camera_right_vector_horizontal = cross(original_camera_forward_vector, world_space_gravity_vector)
```
```
# we want our right vector after rotation to lie in the horizontal plane
assert rotated_camera_right_vector == rotated_camera_right_vector_horizontal
```

Once you have found `theta`, you can either rotate our pre-rendered images by `theta` in image-space, or you can modify our camera poses and re-render images from scratch. In both cases, you'll end up with "upright" images.

**Comment by americast** [comment]
Thanks for your response @mikeroberts3000. I attempted to quickly try out the second method. However, I was unable to find a few files in the repo, namely the `mesh_*`  and `octomap*` data. I am specifically referring to the files being pointed to [here](https://github.com/apple/ml-hypersim/blob/master/code/python/tools/scene_generate_camera_trajectories_random_walk.py#L49-L54). Could you please let me know how I could obtain them?

**Comment by mikeroberts3000** [comment]
From the README,

> To obtain the ground truth triangle meshes for each scene, you must purchase the asset files [here](https://www.turbosquid.com/Search/3D-Models?include_artist=evermotion).

To generate those missing files, you need to purchase all the necessary assets and then re-run our pipeline from the beginning. Note that purchasing the assets will cost roughly $6K USD, and re-rendering our dataset will cost roughly $51K USD. So rotating our pre-rendered images in image space will be a lot cheaper, but re-rendering our dataset from scratch will give you a lot more control over the rendering process.

**Comment by americast** [comment]
I see @mikeroberts3000. Thanks for your response.

> So rotating our pre-rendered images in image space will be a lot cheaper

I should be able to do this without making any purchase right? I guess all the files needed for this purpose (the first method that you outlined) is already provided in the repo?

**Comment by mikeroberts3000** [comment]
Correct.

**Comment by americast** [comment]
Thanks @mikeroberts3000. I am making some assumptions here, but am not sure if they are correct. It would be very helpful if you could please validate. I found mentioned in the README that
> We always set the positive z-axis of our rotation matrix to point up

Following the right hand Cartesian coordinate system, I have assumed, x-axis to point to the right, and y axis to point forward. Accordingly, I have set
```python
original_camera_forward_vector = camera_orientation_matrix[ : , 1]
rotated_camera_right_vector_horizontal = cross(original_camera_forward_vector.T, world_space_gravity_vector)
```
I have assumed `world_space_gravity_vector = array([0, 0, -1])`.

**Comment by mikeroberts3000** [comment]
That quote is from the "3D bounding boxes" section of the documentation, which describes our conventions for 3D bounding boxes we compute around each semantic instance. This is the wrong place to look. The "coordinate conventions" section of the documentation describes our camera conventions. This is the right place to look.

> We store orientations as 3x3 rotation matrices that map points to world-space from object-space, assuming that points are stored as [x,y,z] column vectors. Our convention for storing camera orientations is that the camera's positive x-axis points right, the positive y-axis points up, and the positive z-axis points away from where the camera is looking.

You should make sure you're adhering to our camera conventions. For our scenes, I believe the world-space vector that points from the ground to the sky is `[0 0 1]`. You can use this vector for the gravity vector, or `[0 0 -1]`, as long as you're consistent. Depending on which convention you choose for the gravity vector, you will need to swap the order of the arguments to the cross product operator. If you do the cross product backwards, you'll end up computing the roll angle that rotates the image to be exactly upside down, instead of exactly upright.
