### ISSUE TITLE
segmentation, surface normal, and depth maps

### ISSUE THREAD

**Issue by weihaox** [apple/ml-hypersim#2]
Thank you for the awesome work!

I wonder if it would be better if releasing a version that contains color images and corresponding segmentation, surface normal, and depth maps to facilitate researchers.

**Comment by Kay-byt** [comment]
Excellent work but its needs some work

**Comment by mikeroberts3000** [comment]
The images that you're talking about (i.e., color, segmentation, surface normal, depth, and others) are contained in the publicly available ZIP files and discussed explicitly in the README. Comment here if you have any questions about accessing the data in the ZIP files after reading the README.
