### ISSUE TITLE
Creating the file metadata_cameras_asset_export.csv

### ISSUE THREAD

**Issue by cartacamilla** [apple/ml-hypersim#27]
Hi,

I was wondering if you could give a bit more informations about the file `metadata_cameras_asset_export.csv` that you use for creating the camera metadata. 
If I understand correctly, it should be the same file that is contained in each scene under `_detail/mesh` in `metadata _cameras.csv`.
Is it a file you create separately from the vrscene metadata? Can it be created automatically from 3dsmax or do you create it manually? 
Also, concerning the files `cam_my_camera_X.csv`, are they also created from 3dsmax? 

An unrelated question: I would like to render ai_001_001 with a different fov, but I'm having trouble identifying where it is defined. I changed the fov of the camera in the original .max and when rendering with vray externally to your code I can see the change. When using `dataset_render_scene.py` of the same modified scene, I obtain the old fov view. Is one of the parameterOverrides in `dataset_render_scene.py` overriding the fov to your knowledge?

Thank you for your time.

**Comment by mikeroberts3000** [comment]
Hi! Great questions.

Unfortunately, we couldn't include our code for exporting scene data out of 3ds Max in this repository. So you need to write your own exporter, but it's pretty easy. Your exporter just needs to generate data in the format that the rest of our pipeline is expecting. Have a look [here](https://github.com/mikeroberts3000/ml-hypersim/blob/master/code/python/tools/dataset_export_scenes.py) and [here](https://github.com/mikeroberts3000/ml-hypersim/blob/master/code/python/tools/_dataset_export_scenes.py) for some example code.

When we're exporting our scene data out of 3ds Max, we must export information about each camera in the scene. The purpose of `my_dataset/my_scene_N/_asset_export/metadata_cameras_asset_export.csv` is to declare all the cameras that we export. We need to create this file manually in our exporter. Suppose we export three cameras from 3ds Max. At export time, we must give each of these cameras a unique name. For this example, let's suppose we decide to name the cameras `cam_my_camera_00`, `cam_my_camera_01`, `cam_my_camera_02`. The contents of `metadata_cameras_asset_export.csv` should be as follows:

```
camera_name
cam_my_camera_00
cam_my_camera_01
cam_my_camera_02
```

For each of these cameras, we must create a corresponding CSV file in the `my_dataset/my_scene_N/_asset_export` directory. The CSV file must have the same name as the camera, e.g., `cam_my_camera_00.csv`, `cam_my_camera_01.csv`, `cam_my_camera_02.csv`. We need to create each of these files manually in our exporter.

This exported camera data is eventually consumed [here](https://github.com/apple/ml-hypersim/blob/master/code/python/tools/scene_generate_camera_trajectories_asset_export.py).

Note that `my_dataset/my_scene_N/_asset_export/metadata_cameras_asset_export.csv` isn't exactly the same as `my_dataset/my_scene_N/_detail/metadata_cameras.csv`. In `metadata_cameras_asset_export.csv` the cameras can have any names, but in `metadata_cameras.csv` they get renamed to standard names that are used throughout the rest of our pipeline `cam_00`, `cam_01`, `cam_02`.

Can you ask your FOV question in a separate thread, so it'll be easier for other folks to find it? I'll answer in the new thread.

**Comment by cartacamilla** [comment]
Thank you for your quick reply! I create a separate issue for the second question.
