### ISSUE TITLE
Rendering with different FOV

### ISSUE THREAD

**Issue by cartacamilla** [apple/ml-hypersim#28]
Hi!

I would like to render ai_001_001 with a different FOV, but I'm having trouble identifying where it is defined. I changed the FOV of the camera in the original .max and when rendering with VRay externally to your code I can see the change. When using `dataset_render_scene.py` of the same modified scene, I obtain the old FOV view. Is one of the parameterOverrides in `dataset_render_scene.py` overriding the fov to your knowledge?

Also, is there a better way to change the FOV than what I'm currently doing?

**Comment by mikeroberts3000** [comment]
Hi! Great question. We define the FOV globally [here](https://github.com/apple/ml-hypersim/blob/master/evermotion_dataset/_vray_user_params.py).

You have several options to experiment with different FOV values. You could edit your vrscene file directly (see link above for where to edit). Or you could invoke `vray` on the command-line directly (without going through our `dataset_render_scene.py` wrapper) and set your own `parameterOverride` arguments. Or you could edit our global `_vray_user_params.py` file and re-run our pipeline from `dataset_modify_vrscenes_for_hypersim_rendering.py` onwards.
