### ISSUE TITLE
360 images

### ISSUE THREAD

**Issue by manurare** [apple/ml-hypersim#31]
Hi!

Are 360 equirectangular images shipped with the dataset itself along with its depth correspondence? I guess if not we could render them from the mesh.

Thanks!

**Comment by mikeroberts3000** [comment]
Hi! Great question.

We don't include 360 panorama images with our public release. The good news is that it's an easy one-line change to `_vray_user_params.py` to render 360 panorama images. The bad news is that you need to purchase the assets ($6K) and pay for cloud rendering ($51K).
