### ISSUE TITLE
Mesh files are missing?

### ISSUE THREAD

**Issue by ksaito-ut** [apple/ml-hypersim#32]
Hi, thanks for publishing a very interesting dataset!

When I am trying to run code/python/tools/scene_generate_images_bounding_box.py, I found that the code assumes mesh files (mesh_objects_sii.hdf5, metadata_semantic_instance_colors.hdf5, metadata_semantic_colors.hdf5) under _detail/mesh directory. 

But, the downloaded directories contain only metadata_semantic_instance_bounding_box_object_aligned_2d_extents.hdf5, metadata_semantic_instance_bounding_box_object_aligned_2d_orientations.hdf5, metadata_semantic_instance_bounding_box_object_aligned_2d_positions.hdf5. 

I downloaded ai_001_001.zip and ai_001_002.zip following the URLs in dataset_download_images.py. 
Both zips did not contain mesh files (mesh_objects_sii.hdf5, metadata_semantic_instance_colors.hdf5, metadata_semantic_colors.hdf5). 

Is there anything I am missing? or the mesh files are missing now? 

Thanks in advance!

**Comment by mikeroberts3000** [comment]
Hi! Unfortunately we couldn't publicly release the mesh data. All the mesh data is publicly available, but not from us. In other words, you need to pay for it. We provide pointers in the README.
