### ISSUE TITLE
Is it possible to generate a wireframe image of all the objects in a scene?

### ISSUE THREAD

**Issue by liuzhy71** [apple/ml-hypersim#35]
Thank you for your excellent work.

I am not familiar with the render process of the dataset. I wonder if it is possible to render a image only containing the wireframe of the objects in the scene and the background? Is there any document that I can follow?

**Comment by mikeroberts3000** [comment]
Great question. Yes, this is possible. You can run our labeling tool in "screenshot mode", which will generate wireframe images like this.

![image](https://user-images.githubusercontent.com/2341965/132787282-8ef9655f-1e24-4d0e-86e4-f0cc7bcd5acf.png)

See [here](https://github.com/apple/ml-hypersim/blob/master/code/cpp/tools/scene_annotation_tool/main.cpp#L448) for details. Note that this rendering mode is actually rendering the scene as solid opaque triangles with lines overlaid. If you want to only render lines (without the solid opaque triangles), you'll need to modify our rendering code slightly. But this is a very straightforward modification. Note also that running our annotation tool requires obtaining the source 3D assets. We don't distribute these, so you need to purchase and download them separately. See our README for details.

**Comment by liuzhy71** [comment]
Thank you!!!
