### ISSUE TITLE
Building the annotation tool on ubuntu

### ISSUE THREAD

**Issue by liuzhy71** [apple/ml-hypersim#36]
I am now building the scene annotation tool on ubuntu 18.04. But I notice that the makefile are for Mac OS (after all it is an Apple dataset). Is there any successful example for building the tool on Linux? What should I modify in the case?

**Comment by mikeroberts3000** [comment]
Hi! Great question. We would love it if all of the Hypersim code is easy to set up on Linux. The reason all of the code was tested primarily on macOS is because that was my development environment when I was writing the code, not because I worked at Apple at the time :smile:

That being said, I don't think there should be any issues building the scene annotation tool on Linux. You might not even need to modify our makefile at all. Just specify the appropriate paths in your `system_config.inc` file. All of the dependencies that are required to build the annotation tool are cross-platform and well-supported on Linux: args, armadillo, embree, hdf5, IconFontCppHeaders, libigl

**Comment by mikeroberts3000** [comment]
Oh. Actually, there is a tiny bit of platform-specific code in the tool itself. But you might be able to avoid this issue completely, depending on what you want to do.

If you just want to save a wireframe screenshot, I don't think you need to do anything.

If you want to do more than that, there is one function you'll need to re-write. The `open_directory_dialog` function launches an "open directory" modal dialog box, blocks until the user selects a directory, and returns the selected directory as a string.

```
std::string open_directory_dialog()
```

You'll either need to replace this function with an equivalent function in Linux, or add some command-line arguments to the tool so you never need to call this function for your use case. If you figure out a clean and compact way of launching "open directory" dialog boxes on Linux, please submit a pull request or post here with your findings. I'd love to have a working code example. Note that I wasn't willing to introduce a dependency on a heavyweight GUI library like Qt just for this purpose, so it would be nice to have clean concise native macOS and Linux implementations in the same function guarded by some #ifdefs.

**Comment by liuzhy71** [comment]
I just finishing building the tool. And I am about to ask about the open_directory nor working thing.

This is soooo surprising. Took the words out of my mouth!!!!

Thank you very much.

**Comment by Haiyunn** [comment]
@liuzhy71  Hello,I would like to ask about the complete toolchain and environment you are using to deploy and run this tool. I have tried to set it up under Windows + WSL2 / WSLg (Ubuntu 22.04), but during the final GUI stage, I frequently encounter black screens or crashes. Therefore, I suspect that this issue may be caused by incompatibilities between the environment and the toolchain.

Would you mind sharing the full toolchain configuration that you use to successfully and stably run this tool on native Ubuntu (e.g., OS version, graphics stack, GPU/driver, OpenGL/GLFW, etc.)? Thank you very much!

**Comment by Haiyunn** [comment]
> Oh. Actually, there is a tiny bit of platform-specific code in the tool itself. But you might not need to worry about it, depending on what you want to do.
> 
> If you just want to save a wireframe screenshot, I don't think you need to do anything.
> 
> If you want to do more than that, there is one function you'll need to consider. The `open_directory_dialog` function launches an "open directory" modal dialog box, blocks until the user selects a directory, and returns the selected directory as a string.
> 
> ```
> std::string open_directory_dialog()
> ```
> 
> You'll either need to replace this function with an equivalent function in Linux, or add some command-line arguments to the tool so you never need to call this function for your use case. If you figure out a clean and compact way of launching "open directory" dialog boxes on Linux, please submit a pull request or post here with your findings. I'd love to have a working code example. Note that I wasn't willing to introduce a dependency on a heavyweight GUI library like Qt just for this purpose, so it would be nice to have clean concise native macOS and Linux implementations in the same function guarded by some #ifdefs.




I worked it out with the following code:


std::string open_directory_dialog() {

    // HACK: only works on ubuntu
    const int FILE_DIALOG_MAX_BUFFER = 4096;
    char buffer[FILE_DIALOG_MAX_BUFFER];
    FILE * output = popen(
        "zenity --file-selection --directory --title=\"选择文件夹\" 2>/dev/null | tr -d '\n' ","r");

    while (fgets(buffer, FILE_DIALOG_MAX_BUFFER, output) != NULL) {}
    if (!filesystem_exists(buffer)) {
        return "";
    } else {
        return buffer;
    }
}

**Comment by mikeroberts3000** [comment]
This is great! Thank you! Feel free to submit a PR with this change. If you do decide to submit a PR, here are some minor things to address.

1. I asked ChatGPT to review the original function and it correctly identified the following issues:

> What’s questionable in the current pattern:
> - You never pclose(output). That leaks the process handle and can leave zombies on POSIX.
> - buffer may be uninitialized / stale. If popen() fails, or if the command produces no output (user cancels), your loop never writes to buffer, and you then call filesystem_exists(buffer) on garbage from the stack. Fix: set buffer[0] = '\0' up front, and handle output == nullptr.
> - You’re discarding all but the last fgets() chunk. Your loop keeps overwriting buffer and then stops at EOF; if the output is longer than 4096 or contains multiple lines, you’ll only end up with the last chunk. For file paths, you probably want to accumulate into a std::string (or at least break after the first line).
> - Cancel behavior. Both AppleScript choose folder and zenity --file-selection typically emit nothing (or return non-zero) when canceled. Your current code should treat that as "" reliably.
> - Trailing newline stripping. tr -d '\n' is okay, but you can also just strip in C++ and avoid depending on tr.

2. Remove the non-English characters from the Linux code snippet.

3. Use ifdefs in the function to isolate the platform-specific parts of the function, such that there is a minimal amount of platform-specific code inside the ifdefs.
