### ISSUE TITLE
Problems about the windows vray environment setting

### ISSUE THREAD

**Issue by liuzhy71** [apple/ml-hypersim#37]
To convert a .max scene sample to .vrscene, I switch to the windows platform to use 3ds max. 

However, I failed to configure the vray as the README in windows. The vray for linux works fine with my PC

What version of vray do I need? Vray standalone or Vray for 3ds Max? What modifications do I need?

Currently, I'm using 3ds max with vray for 3ds max. And I also installed vray standalone and vray app sdk. Is there something wrong?

Need some guidance on this.

**Comment by mikeroberts3000** [comment]
Great questions. What specific errors are you seeing? I think you need a specific version of 3ds Max. I know that 3ds Max 2018 update 4 works. I have heard from other users that 3ds Max 2019 also works but 3ds Max 2022 doesn't. For maximum compatibility with our code, it is probably best to stick to the versions of V-Ray that we mention in the README.

**Comment by liuzhy71** [comment]
I am using 3ds max 2020. However, my main problem is about the vray in windows. So, should I use the standalone vray and 3ds max?

**Comment by mikeroberts3000** [comment]
What step from our README are you attempting to run, and what errors are you seeing?

**Comment by liuzhy71** [comment]
Right now, it is a qt problem with the 3ds max. 3ds max has its own qt lib. And I have an error of 

```This application failed to start because no Qt platform plugin could be initialized``` when running the python vray codes.

**Comment by mikeroberts3000** [comment]
What script are you attempting to run?
