### ISSUE TITLE
Projection setting of the dataset

### ISSUE THREAD

**Issue by liuzhy71** [apple/ml-hypersim#40]
When using the `scene_annotation_tool` to generate images, I found that, in some scenes, the camera projections from the scene_annotation_tool are different from the rendered images. 

For example, in scene `ai_026_006` the render image of `cam_00` with id `0097` is 
![frame 0097 tonemap](https://user-images.githubusercontent.com/16524611/137332947-2dc5f0fb-fbe0-4a0e-87ad-5767d7785771.jpg)

However, the screen shot from the annotation tool is
![screenshot](https://user-images.githubusercontent.com/16524611/137332858-ad71a2d6-60d2-48d5-9fda-61a88cb2f183.png)

It can be seen that in the annotation tool, the distortion of post is small. However, in the original image the distortion is distinct.

How can I fix this problem to generate correct images from the annotation tool?

**Comment by liuzhy71** [comment]
[camera_data_out_new.csv](https://github.com/apple/ml-hypersim/files/7532163/camera_data_out_new.csv)
This is a vray camera data that I parsed and I have manually examined all the scenes for the projection alignment. Hope this helps anyone working on this problem.

**Comment by mikeroberts3000** [comment]
Hi @liuzhy71, I have some good news. I just checked in some data and example code that addresses this issue.

In the [`contrib/mikeroberts3000`](https://github.com/apple/ml-hypersim/tree/master/contrib/mikeroberts3000) directory, I provide a modified perspective projection matrix for each scene that can be used as a drop-in replacement for the usual OpenGL perspective projection matrix, as well as example code for projecting world-space points into Hypersim images.

I apologize that it took so long to address this issue. It was especially challenging to debug because V-Ray's behavior wasn't well-documented and I've been slammed with other projects.

**Comment by liuzhy71** [comment]
> Hi @liuzhy71, I have some good news. I just checked in some data and example code that resolves this issue.
> 
> In the [`contrib/mikeroberts3000`](https://github.com/apple/ml-hypersim/tree/master/contrib/mikeroberts3000) directory, I provide a modified perspective projection matrix for each scene that can be used as a drop-in replacement for the usual OpenGL perspective projection matrix, as well as example code for projecting world-space points into Hypersim images.
> 
> I apologize that it took so long to address this issue. It was especially challenging to debug because V-Ray's behavior wasn't well-documented, and I've been busy with other projects and holiday travel.

wow, thank you very much, I have made a work around of the projection matrix. But I didn't test it thoroughly, I'll cross compare them to check if my work around is right.

**Comment by liuzhy71** [comment]
> Hi @liuzhy71, I have some good news. I just checked in some data and example code that resolves this issue.
> 
> In the [`contrib/mikeroberts3000`](https://github.com/apple/ml-hypersim/tree/master/contrib/mikeroberts3000) directory, I provide a modified perspective projection matrix for each scene that can be used as a drop-in replacement for the usual OpenGL perspective projection matrix, as well as example code for projecting world-space points into Hypersim images.
> 
> I apologize that it took so long to address this issue. It was especially challenging to debug because V-Ray's behavior wasn't well-documented, and I've been busy with other projects and holiday travel.

wow, thank you very much, I have made a work around of the projection matrix. But I don't test it thoroughly,
