### ISSUE TITLE
Illumination Information

### ISSUE THREAD

**Issue by arjunsinghrathore** [apple/ml-hypersim#43]
Hi! So i wanted to know that how are you guys storing the illuminant color information for the scene? Is it for the raw hdf5 images or the tone mapped/non linear transformed image? As I was trying to save the illuminant information by saving thr input RGB values in blender. And this works for images when I'm rendering them with no non linear transformation. But when i add non linear transformation like Filmic tone mapping then the input RGB values given to blender and the illuminant color we can roughly identify from eye seems to be pretty different in some cases. So I wanted to know that how are you guys saving the illuminant if you're doing tone mapping as well?

**Comment by mikeroberts3000** [comment]
Hi Arjun, I'm not sure I understand your question. There is no tone-mapping in any of our HDF5 files. Our HDF5 data adheres to the following equation with very low error:

```
color == diffuse_reflectance*diffuse_illumination + residual
```

We eventually do compute tone-mapped images, but we only save them as JPG files.
