### ISSUE TITLE
generate 3D bounding boxes 

### ISSUE THREAD

**Issue by dferthvf** [apple/ml-hypersim#48]
Hi, when I tried to use the script "scene_generate_images_bounding_box.py" to generate bounding boxes, I wondered what is the difference between bounding_box_type == "object_aligned_2d" and bounding_box_type == "object_aligned_3d".

**Comment by mikeroberts3000** [comment]
Hi, great question. The `object_aligned_2d` method is the one described in the main README. Using this method, one of the bounding box's axes is always aligned with the world-space up vector (i.e., the gravity vector), and the other two axes are computed such that the bounding box has minimum area. The `object_aligned_3d` method computes the minimum-volume bounding box, and in general does not produce bounding boxes that are aligned with the world-space up vector.
