### ISSUE TITLE
rotation and translation matrix

### ISSUE THREAD

**Issue by SyanneL** [apple/ml-hypersim#53]
Hi, thanks for your great work! I am wondering if the rotation matrix in camera_keyframe_orientations.hdf5 and translation matrix in camera_keyframe_positions.hdf5 are camera to world or world to camera?

**Comment by mikeroberts3000** [comment]
Hi! From our README.

> `camera_keyframe_orientations.hdf5` contains an Nx3x3 array of camera orientations, where N is the number of frames in the trajectory, and **each orientation is represented as a 3x3 rotation matrix that maps points to world-space from camera-space, assuming that points are stored as [x,y,z] column vectors**. The convention in the Hypersim Dataset is that the camera's positive x-axis points right, the positive y-axis points up, and the positive z-axis points away from where the camera is looking.
> 
> `camera_keyframe_positions.hdf5` contains an Nx3 array of camera positions, where N is the number of frames in the trajectory, and each position is stored in [x,y,z] order. These positions are specified in asset coordinates.

**Comment by air158** [comment]
Is "positions" the world coordinates of the camera?
