### ISSUE TITLE
Question for V-Ray version

### ISSUE THREAD

**Issue by hbbOooO** [apple/ml-hypersim#55]
Hi, authors. Thank you for this wonderful work.
I want to install The Hypersim Toolkit on my PC, but I met some  problems when installing V-Ray Standalone and the V-Ray AppSDK: These files end with "*.dylib" are not in the folder "/Applications/ChaosGroup/V-Ray/AppSDK/bin/". I guess my version about AppSDK is wrong.
So, I want to know more details including:
1. The OS system. Ubuntu or CentOS?
2. Version of V-Ray Standalone and AppSDK. I choose [V-Ray 5 Standalone, update 2.1 (Zip)](https://download.chaos.com/api/v1/builds/19318/download) and [V-Ray AppSDK 1.24.03 Standalone 3.60.04 ADV](https://download.chaos.com/api/v1/builds/9422/download).

Thanks!

**Comment by mikeroberts3000** [comment]
Hi!

I have successfully run the Linux parts of the toolkit on Ubuntu (I don't remember exactly which version, but it would have been whatever the LTS version was in 2020). For V-Ray, I used the _Next Standalone update 2.1_ version of V-Ray Standalone and the AppSDK. It should be fine to work with a different version of V-Ray, as long as the Standalone version matches the AppSDK version, but the setup instructions will probably vary slightly.

Ultimately, you just need to make sure that you can `import vray` and use the `vray` module from the Python environment you're using to execute our code. If you can `import vray` and use it, then the AppSDK is installed correctly.
