### ISSUE TITLE
How to get point cloud?

### ISSUE THREAD

**Issue by zou-longkun** [apple/ml-hypersim#57]
Hello, I want to get a point cloud from a depth scene image. I use the given camera parameters, but the obtained point cloud has certain distortion. Can you explain it?

**Comment by mikeroberts3000** [comment]
Hi!

Our depth images are actually measuring Euclidean distance to the camera, not planar depth. See https://github.com/apple/ml-hypersim/issues/9 for more details. If you're using depth images to obtain a point cloud, you need to take this nuance into account. And to be 100% correct, you will also need to take into account our per-scene camera intrinsics. See [here](https://github.com/apple/ml-hypersim/tree/main/contrib/mikeroberts3000) for more details.

But actually none of the above steps are necessary. We release `world_space_position` images, and you can simply reshape these images from `[H, W, 3]` to `[H*W, 3]` and concatenate them together to obtain a consistent world-space point cloud.
