### ISSUE TITLE
Obtaining pre-rendered semantic segmentation 

### ISSUE THREAD

**Issue by s1ddok** [apple/ml-hypersim#6]
Hi!

I'm trying to extract a simple subset of ml-hypersim - final color images + semantic labels (with ids, without instances)

I've spent some time trying to get `dataset_generate_images_semantic_segmentation.py` to work but failed to. Mostly because of lacking `mesh` directory inside downloading datasets.

What I don't understand is why this script cannot just read `frame.NNNN.semantic.hdf5` files and save them as png but instead uses this code:

```python
# nodes are assigned render_entity_ids 1 to N, and all lights are set to invisible, so we should never encounter a render_entity_id greater than node_id_max
    assert all(logical_or(render_entity_id_img == -1, logical_and(render_entity_id_img >= 1, render_entity_id_img <= node_id_max)))
    mesh_object_id_img[render_entity_id_img != -1] = node_ids_to_mesh_object_ids[render_entity_id_img[render_entity_id_img != -1]]

    assert all(logical_or(mesh_object_id_img == -1, logical_and(mesh_object_id_img >= 0, mesh_object_id_img <= mesh_object_id_max)))
    segmentation_id_img[mesh_object_id_img != -1] = mesh_object_ids_to_segmentation_indices[mesh_object_id_img[mesh_object_id_img != -1]]

    assert all(logical_or(segmentation_id_img == -1, logical_and(segmentation_id_img >= 1, segmentation_id_img <= segmentation_id_max)))
    segmentation_color_img[segmentation_id_img != -1] = segmentation_ids_to_segmentation_colors[segmentation_id_img[segmentation_id_img != -1]]
```

Do I understand correctly that this script is only for power users who do their own cloud storage and for oridinary pre-rendered use one can simply read existing hdf5 files without any post-processing (like those node_id_max things)?

Thanks for help! Sorry if the question is too newbie.

**Comment by mikeroberts3000** [comment]
Hi! The images you care about are stored directly in the ZIP files that you can download. For example:

```
ai_001_001/images/scene_cam_XX_final_hdf5/frame.0000.color.hdf5 # color image before any tonemapping has been applied
ai_001_001/images/scene_cam_XX_geometry_hdf5/frame.0000.semantic.hdf5 # semantic IDs using NYU40 labels
```

HDF5 files are multi-dimensional array files that are easy to read and write from C++ and Python. See our usage of the `h5py` module throughout the code for examples on how to load these files into NumPy arrays. It is only necessary to run `dataset_generate_images_semantic_segmentation.py` if you have re-labeled the meshes or if you're doing your own rendering.

I hope that helps! Also, thank you for your contribution to the download script 😀

**Comment by mikeroberts3000** [comment]
Hi @phongnhhn92, yes, we're recommending using the HDF5 files for downstream learning tasks, because otherwise you're discarding a lot of useful information. We implement a simple tonemapping operator in `python/tools/scene_generate_images_tonemap.py` that is only a few lines of code. Use that as a starting point.

(If you want to get fancy, you could also randomize the tonemapping parameters during training, which is roughly equivalent to augmenting your dataset with multiple exposures of the same image.)
