### ISSUE TITLE
Semantic labels for point cloud data

### ISSUE THREAD

**Issue by OrangeSodahub** [apple/ml-hypersim#64]
Great dataset! And I want to get the semantic labels for point cloud data. Following the previous issues, the point cloud data could be formed from the concatenation of all the position images of each scene, however how to get the label id for each pixel/point? I ran the script `code/python/tools/dataset_download_images.py` and get the correspoinding semantic images, but no where to find the actual semantic labeled data, except the mesh files, while I just don't want mesh files now.

Thanks!

**Comment by mikeroberts3000** [comment]
I'm not sure I understand your question. The value at each pixel in a `position` image is a 3D point in world space. You can therefore construct a dense point cloud by concatenating multiple of these points together, either from the same image or multiple images. You can find the semantic label of each point by examining its corresponding pixel in our `semantic` images.

Maybe I'm not understanding your question. Can you elaborate?

**Comment by OrangeSodahub** [comment]
@mikeroberts3000 Hi, thanks! Sorry of the unclear expression. So I can fetch the `frame.0001.semantic.hdf5` to examine the semantic id for each pixel, and it's nyu40 id? And is there any public released map file here so I could get its string label for each semantic id?

**Comment by OrangeSodahub** [comment]
And another question, for example: `ai_001_001/images/scene_cam_00_geometry_preview/frame.0000.semantic.png`:
![image](https://github.com/apple/ml-hypersim/assets/54439582/ddd15f1d-10c9-43fd-acfd-f9af6d378701)
It seems that it doesnt't sepcify the `ceiling` and the `wall` how can I get their pixel labels? Thanks!

**Comment by OrangeSodahub** [comment]
@mikeroberts3000 Big thanks! Now all questions have been solved for me
