### ISSUE TITLE
About error pose in some scene

### ISSUE THREAD

**Issue by myc634** [apple/ml-hypersim#78]
Hi,

Thanks for your great work!

However, while I using gt depth and pose to performing warping, it sometimes fail in certain scene. I found my code failed on scenes `ai_019_001`, `ai_007_005`, but it can perform correct warping operation on scenes such as `ai_001_002` and `ai_003_009`. Is there anything I missed or is the pose in these scenes incorrect? I can provide the code of warping / projection if you need.

Many thanks if you can help

**Comment by myc634** [comment]
Oh I find is due to the `M_cam_from_uv` mat is little bit different, could you please tell me why? or is their any general method to transform `M_cam_from_uv` into standard OpenCV intrinsics

**Comment by mikeroberts3000** [comment]
The non-standard camera intrinsics found in some scenes are documented extensively [here](https://github.com/apple/ml-hypersim/tree/main/contrib/mikeroberts3000).
