### ISSUE TITLE
Obtaining mask for diffuse reflectance

### ISSUE THREAD

**Issue by KoykL** [apple/ml-hypersim#8]
Thank you so much for your great work! I have a question about diffuse reflectance:

There are two cases that diffuse reflectance will be close to zero: 1. the region contains translucent/metallic/etc objects 2. the region actually contains black objects. Is it possible to distinguish between these two cases? e.g. Maybe there are ways to obtain masks for translucent/metallic/etc regions? Thank you for the help.

**Comment by mikeroberts3000** [comment]
Hi! I'm not sure I understand the question. I'm going to try and rephrase your question. Can you tell me if I rephrased it correctly?

> Suppose there is a pixel `p` such that:
> 
> ```
> final_color[p]          == 0.0
> diffuse_reflectance[p]  == 0.0
> diffuse_illumination[p] == 1.0
> residual[p]             == 0.0
> ```
> 
> Is there any way to to tell whether the surface at `p` is: (a) a diffuse black object (e.g., a black bar of soap); or (b) a perfectly specular mirror that is showing the reflected image of a diffuse black object? In both cases, the values for `final_color[p]`, `diffuse_reflectance[p]`, `diffuse_illumination[p]`, and `residual[p]` would be identical.

Am I understanding your question correctly? 🤓

**Comment by KoykL** [comment]
Thank you so much for the help and detailed instructions! Unfortunately I cannot afford the assets.

But I am trying to resolve a slightly different ambiguity, so maybe this can be done? For example:
1. We have a specular black object (e.g. black plastic)
2. We have a mirror (reflecting arbitrary objects)
3. We have a shiny metal (e.g. copper/stainless steel)
4. We have a window

I am trying to separate 1 from 2&3&4. 
Final color: In all four cases, the final color is non zero. (final color is nonzero for 1 due to specularity. the magnitude of final color can be different from 1 to 2&3&4)
Diffuse reflectance: In all four cases, the diffuse reflectance is close to zero. 
Diffuse illumination: For 1, diffuse illumination is non zero. For 2, 3, 4, diffuse illumination can be either 0 or non-zero depending on the scene.
Residual: The residual is non zero for all four cases, but the magnitude can be different.

I guess the best solution is try to figure out a threshold on magnitude on residual/final color to separate 1 from the rest?

**Comment by mikeroberts3000** [comment]
Ah I understand. Unfortunately, what you want to do is not possible without purchasing the assets, and parsing the V-Ray scene description file as I described above.

Alternatively, if anyone is reading this and wants to re-render their own images anyway, it is possible to output more fine-grained lighting and shading information than we do in Hypersim. In particular, it is possible to distinguish between specular, reflective, and refractive surfaces by configuring V-Ray to output the following render elements: [VRaySpecular](https://docs.chaosgroup.com/display/VMAX/VRaySpecular), [VRayReflection](https://docs.chaosgroup.com/display/VMAX/VRayReflection), and [VRayRefraction](https://docs.chaosgroup.com/display/VMAX/VRayRefraction).

(However, I don't believe outputting these render elements would distinguish between a specular black object and a shiny metal object. In both cases, the non-diffuse energy would be contained in the VRaySpecular render element. To make such a fine-grained distinction, I believe it would be necessary to parse the materials in the scene description file.)
